config/routes.rb
Rails.application.routes.draw do
  resources :phsicians
  resources :patients
  resources :tags
  resources :categories
  #resources :blogs
  resources :appointments
  resources :blogs do
    member do
      get :get_dataset
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  get "dashboard", to: "dashboard#index"
  resources :users, except: [:new]
end

app/models/patient.rb
class Patient < ApplicationRecord
    validates :name,  presence: true, length: { maximum: 50 }
    validates :email,  presence: true,uniqueness: true, length: { maximum: 50 }
    has_many :appointments
    has_many :phsicians, through: :appointments
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[ show edit update destroy ]
  layout 'custom'

  # GET /patients or /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1 or /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients or /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully created." }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully updated." }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url, notice: "Patient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:name, :email)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_with(model: patient) do |form| %>
  <% if patient.errors.any? %>
    <div style="color: red">
      <ul>
        <% patient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class: "form-control" %>
  </div>
  <br>
  <div>
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/patients/_patient.html.erb
<div id="<%= dom_id patient %>">
  <p>
    <strong>Name:</strong>
    <%= patient.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= patient.email %>
  </p>

</div>

app/views/patients/edit.html.erb
<h3>Editing patient</h3>

<%= render "form", patient: @patient %>

<br>

<div>
  <%= link_to "Show this patient", @patient %> |
  <%= link_to "Back to patients", patients_path %>
</div>

app/views/patients/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#">Home</a></li>
    <li class="breadcrumb-item"><a href="#">Patients</a></li>
    <li class="breadcrumb-item active" aria-current="page">list</li>
  </ol>
</nav>

<table class="table table-bordered table-striped" id="myTable">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  
  <% @patients.each do |c| %>
    <tr>
      <th scope="row"><%= c.id%></th>
      <td><%= c.name %></td>
      <td><%= c.email %></td>
      <td>
          <%= link_to 'Edit', {:action => 'edit', :id => c.id}, class: "btn btn-primary btn-sm" %>&nbsp;&nbsp;&nbsp;
          <%= button_to 'Delete', patient_path(c), method: :delete, class: "btn btn-danger btn-sm" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to "New Patient", new_patient_path, class: 'btn btn-primary' %>
<script>
$(document).ready( function () {
    $('#myTable').DataTable();
} );
</script>

app/views/patients/new.html.erb
<h3>New patient</h3>

<%= render "form", patient: @patient %>

<br>

<div>
  <%= link_to "Back to patients", patients_path %>
</div>

app/views/patients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @patient %>

<div>
  <%= link_to "Edit this patient", edit_patient_path(@patient) %> |
  <%= link_to "Back to patients", patients_path %>
  <br><br>
  <%= button_to "Destroy this patient", @patient, method: :delete, class: "btn btn-danger" %>
</div>