config/routes.rb
Rails.application.routes.draw do
  resources :phsicians
  resources :patients
  resources :tags
  resources :categories
  #resources :blogs
  resources :appointments
  resources :blogs do
    member do
      get :get_dataset
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  get "dashboard", to: "dashboard#index"
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
    belongs_to :patient, optional: true
    belongs_to :phsician
    validates :appointment_date,  presence: true
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :category
    has_and_belongs_to_many :tags
    mount_uploader :attachment, AttachmentUploader
    has_one_attached :attachment
    validates :title,  presence: true, length: { maximum: 50 }
    validates :tags,  presence: { message: 'field is required'}
    validates :attachment,  presence: { message: 'field is required'}
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :blogs
end

app/models/patient.rb
class Patient < ApplicationRecord
    validates :name,  presence: true, length: { maximum: 50 }
    validates :email,  presence: true,uniqueness: true, length: { maximum: 50 }
    has_many :appointments
    has_many :phsicians, through: :appointments
end

app/models/phsician.rb
class Phsician < ApplicationRecord
    validates :name,  presence: true, length: { maximum: 50 }
    validates :email,  presence: true, uniqueness: true, length: { maximum: 50 }
    has_many :appointments
    has_many :patients, through: :appointments
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_and_belongs_to_many :blogs
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :username,  presence: false, length: { maximum: 50 }
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  layout 'custom'
  
  def new
    @blog = Blog.new
    @category = Category.all
  end

  def create
    @blog = Blog.new(blog_params)
    #@blog.tag_ids = params[:tag_ids]
    if @blog.save
       redirect_to :action => 'index'
    else
      respond_to do |format|
        format.html{
          render :new,
          status: :unprocessable_entity
        }
      end
    end
  end

  def update
    @blog = Blog.find(params[:id])
     
    if @blog.update(blog_params)
       redirect_to :action => 'index', :id => @blog
    else
       render :action => 'edit'
    end
  end

  def edit
    @blog = Blog.find(params[:id])
    @category = Category.all
  end

  def destroy
    Blog.find(params[:id]).destroy
     redirect_to :action => 'index'
  end

  def index
    @blogs = Blog.all
    respond_to do |format|
      format.html
      format.json { render json: UserDatatable.new(blog_params) }
    end
  end

  def show
  end

  def blog_params
    params.require(:blog).permit(:title, :description,:attachment, :category_id,{ tag_ids: [] }, :status)
 end


 def get_processed_dataset
  lines = Category.datatable_filter(params['search']['value'], params['columns'])
    lines_filtered = lines.count
    
    render json: { lines: lines,
                  draw: params['draw'].to_i,
                  recordsTotal: Line.count,
                  recordsFiltered: lines_filtered }
  end

  def get_dataset
    respond_to do |format|
      format.json { render json: Category.all }
    end
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[ show edit update destroy ]
  layout 'custom'

  # GET /patients or /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1 or /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients or /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully created." }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully updated." }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url, notice: "Patient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:name, :email)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  layout 'custom'
  before_action :set_tag, only: %i[ show edit update destroy ]

  # GET /tags or /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1 or /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags or /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tag_url(@tag), notice: "Tag was successfully created." }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to tag_url(@tag), notice: "Tag was successfully updated." }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url, notice: "Tag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new 
        @user = User.new
    end

    def create
        
        @user = User.new(user_params)
        if @user.save
          # Tell the UserMailer to send a welcome email after save
         UserMailer.with(user: @user).welcome_email.deliver_now
        
          flash[:notice] = "User created."
          redirect_to login_path
        else
          respond_to do |format|
            format.html{
              render :new,
              status: :unprocessable_entity
            }
          end
          
        end
      end

      def edit
            
      end
      
     private
      
      def user_params
        params.require(:user).permit(:username, :email, :password)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_class?(test_path)
        return 'active' if request.path.include? test_path
      end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/phsicians_helper.rb
module PhsiciansHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railstest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/custom.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railstest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" />
    <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
    <link href="http://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css" rel="stylesheet">
    <script src="http://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js" async="async" data-turbo-track="reload"></script>
  </head>

  <body>
  <div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                    <span class="fs-5 d-none d-sm-inline">Menu</span>
                </a>
                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                    <%= link_to dashboard_path, :class => "nav-link px-0 align-middle #{current_class?("/dashboard") }" do %>
                         <i class="fa fa-user"></i> <span class="ms-1 d-none d-sm-inline">Dashboard</span>
                    <% end %>
                    </li>
                    
                    <li>
                    <%= link_to categories_path, :class => "nav-link px-0 align-middle #{current_class?("/categories") }" do %>
                         <i class="fa fa-list"></i> <span class="ms-1 d-none d-sm-inline">Categories</span>
                    <% end %>
                    </li>

                    <li>
                    <%= link_to tags_path, :class => "nav-link px-0 align-middle #{current_class?("/tags") }" do %>
                         <i class="fa fa-tag"></i> <span class="ms-1 d-none d-sm-inline">Tags</span>
                    <% end %>
                    </li>

                     <li>
                    <%= link_to patients_path, :class => "nav-link px-0 align-middle #{current_class?("/patients") }" do %>
                         <i class="fa fa-tag"></i> <span class="ms-1 d-none d-sm-inline">Patients</span>
                    <% end %>
                    </li>

                     <li>
                    <%= link_to phsicians_path, :class => "nav-link px-0 align-middle #{current_class?("/phsicians") }" do %>
                         <i class="fa fa-medkit"></i> <span class="ms-1 d-none d-sm-inline">Physicians</span>
                    <% end %>
                    </li>

                     <li>
                    <%= link_to appointments_path, :class => "nav-link px-0 align-middle #{current_class?("/appointments") }" do %>
                         <i class="fa fa-calendar"></i> <span class="ms-1 d-none d-sm-inline">Add Appointment</span>
                    <% end %>
                    </li>

                    <li>
                    <%= link_to blogs_path, :class => "nav-link px-0 align-middle #{current_class?("/blogs") }" do %>
                         <i class="fa fa-newspaper-o"></i> <span class="ms-1 d-none d-sm-inline">Blogs</span>
                    <% end %>
                    </li>

                    <li>
                    <%= link_to 'logout', :class => 'nav-link px-0 align-middle' do %>
                         <i class="fa fa-sign-out"></i> <span class="ms-1 d-none d-sm-inline">Logout</span>
                    <% end %>
                        
                    </li>

                </ul>
                <hr>
                <div class="dropdown pb-4">
                    <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="https://github.com/mdo.png" alt="hugenerd" width="30" height="30" class="rounded-circle">
                        <span class="d-none d-sm-inline mx-1">loser</span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
                        <li><a class="dropdown-item" href="#">New project...</a></li>
                        <li><a class="dropdown-item" href="#">Settings</a></li>
                        <li><a class="dropdown-item" href="#">Profile</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Sign out</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col py-3">
            <%= yield %>
        </div>
    </div>
    </div>
  </body>
</html>